### ISSUE TITLE
Multilanguage support

### ISSUE THREAD

**Issue by FelixINX** [octobercms/docs#118]
OctoberCMS has been translated to 20 language. Why not docs?

**Comment by waipy** [comment]
I have the same question

**Comment by sajjad-ser** [comment]
+1 for this

**Comment by MatissJanis** [comment]
The docs are constantly changing. Introducting multiple languages to the docs would mean that each language needs a manager looking after it and updating as we go. I don't think that this is a good idea at this point in time.

**Comment by lincolnbrito** [comment]
I want to contribute in Brazilian Portuguese - pt_BR

**Comment by vojtasvoboda** [comment]
I also want to create Czech language (cs_CZ) translation.

**Comment by LukeTowers** [comment]
@daftspunk or @alekseybobkov any thoughts on this?

**Comment by FelixINX** [comment]
I will come back to my point ... and say no. The reason for @MatissJanis is very good. But above all, why translate the documentation, if the site is not translated. Ask @daftspunk and @alekseybobkov when the site will be open source, and when we can translate it!
