### ISSUE TITLE
Linking a current page, with parameters

### ISSUE THREAD

**Issue by alekseybobkov** [octobercms/docs#12]
When we need to create a link to the current page and pass parameters to the URL:

```
{{ this.page.baseFileName|page({ page: page }) }}
```

**Comment by KirillArtemenko** [comment]
When we need to create a link to the any page inside component:
```php
use Cms\Classes\Page;
$this->page['link'] = $this->pageUrl('page_filename', ['slug_name' => 'slug_value']);
```

**Comment by daftspunk** [comment]
Documented already

---

You can create a link to the current page by filtering an empty string:

    <a href="{{ ''|page }}">Refresh page</a>
