### ISSUE TITLE
Missing UI and MARKUP docs

### ISSUE THREAD

**Issue by FelixINX** [octobercms/docs#128]
Hi,

The UI and Markup docs are missing :sob: .

**Comment by dshoreman** [comment]
The Markup docs are in [the CMS section](https://octobercms.com/docs/markup). You can find UI docs inside `modules/system/assets/ui/docs`.

**Comment by daftspunk** [comment]
This ^

**Comment by FelixINX** [comment]
Can we make pull request to this docs?

**Comment by daftspunk** [comment]
Of course =)

**Comment by FelixINX** [comment]
Yes, but the docs are not the same as the online version. Ex:
![october docs ui](https://cloud.githubusercontent.com/assets/8009156/10119295/402940c8-6460-11e5-9d2b-dbf6c0e00a8d.png)

You can see there are a lot of difference. I will upload UI docs to this repo, and adjust it with online version if you agree :+1: .

**Comment by FelixINX** [comment]
The `invalid` tag should be removed.
