### ISSUE TITLE
Model `attachOne` and `attachMany` is now missing from re-organised documentation

### ISSUE THREAD

**Issue by jofrysutanto** [octobercms/docs#129]
Can't seem to find the documentation on File attachment anymore?

**Comment by alxy** [comment]
The ``$jsonable`` attribute modifier is also missing in the new docs.

**Comment by daftspunk** [comment]
Fixed in a948ea21ef52490e66da0effdc79f048f2ae0610

**Comment by jofrysutanto** [comment]
Awesome!
