### ISSUE TITLE
[bug] Lots of JS broken on UI docs

### ISSUE THREAD

**Issue by that0n3guy** [octobercms/docs#141]
See here: https://octobercms.com/docs/ui/popup

The example buttons don't work, same with tabs, tooltips, etc...

**Comment by keiosweb** [comment]
+1

```TypeError: (intermediate value)(...) is not a function```

I think that minified JS needs to be regenerated and checked.

**Comment by huseyinkozan** [comment]
+1

**Comment by LukeTowers** [comment]
Sometime between then and now, the JS has been regenerated. Thus, this will be closed :)
