### ISSUE TITLE
Inaccuracy in setup-configuration Nginx configuration paragraph

### ISSUE THREAD

**Issue by pbtlt** [octobercms/docs#142]
If Octobercms  placed in root folder / , folowing rewrite rules won't work:

```
...
rewrite ^bootstrap/.* /index.php break;
rewrite ^config/.* /index.php break;
...
```

Because right path must starts with slash symbol like this:

```
rewrite ^/bootstrap/(.*) /index.php break;
rewrite ^/config/.* /index.php break;
```

Probably if you are under subfolder location like /cms/, maybe rules without forward slash will work. Actually I haven't checked this moment.

**Comment by daftspunk** [comment]
Fixed by #204
