### ISSUE TITLE
Schedule options listed in docs that are not available until L5.1

### ISSUE THREAD

**Issue by jwilson8767** [octobercms/docs#143]
The [docs on task scheduling](https://octobercms.com/docs/plugin/scheduling) list before() and after() as being valid, however they were not introduced until after L5.0. [Here is the commit](https://github.com/laravel/framework/commit/415929a69c8c1bfe0b10b3a90b6216a31c9bbeb9) where before() was added. after() was called then() until [this commit](https://github.com/laravel/framework/commit/fc063229a87ae38ea858067a5054895ac865874c). Anyway, the point is that the [docs on task scheduling()](https://octobercms.com/docs/plugin/scheduling) should use the [L5.0 docs](http://laravel.com/docs/5.0/artisan#scheduling-artisan-commands) (at least until we get up to L5.1)

**Comment by LukeTowers** [comment]
Closing this as October is on Laravel 5.1 LTS now.
