### ISSUE TITLE
Document component partial access to properties

### ISSUE THREAD

**Issue by jwilson8767** [octobercms/docs#148]
`{{__SELF__.property('some-property')}}` should be documented [here](https://octobercms.com/docs/plugin/components#referencing-self) for accessing properties of the component from its partials.

**Comment by LukeTowers** [comment]
@jwilson8767 Add a PR to document it as requested and I'll merge it.

**Comment by LukeTowers** [comment]
Added in https://github.com/octobercms/docs/commit/bd715d26a78be7a4428c07a5f150d634d4f6e34c
