### ISSUE TITLE
More specific how-to's for common needs

### ISSUE THREAD

**Issue by ChadStrat** [octobercms/docs#15]
It would be helpful to have entry point doc's on specific how-to's. Specifically for some of the most common design needs that may have some layer of complexity for newcomers to the platform. (fully aware that in sum all parts seem to be doc'd, but in some cases it's quite spread out and difficult to extrapolate)

This may need to be a simple "Examples" doc area?

Examples:
- Image Slider
- Contact Us Form
- Dynamic/Generated Navigation
  (feel free to add more)

**Comment by LukeTowers** [comment]
If anyone wants to write up a series of tutorials and send a link we can look at linking to it from the docs. However I think those tasks are better suited as pointing to using plugins from the marketplace instead.
