### ISSUE TITLE
Remove database structure section

### ISSUE THREAD

**Issue by yourwebmaker** [octobercms/docs#162]
October's migrations rely on Laravel's migration.

Instead of keeping this documentation section up to date, I suggest to point the user to Laravel's migration docs: https://laravel.com/docs/5.1/migrations

**Comment by daftspunk** [comment]
Thanks for the suggestion!

**Comment by yourwebmaker** [comment]
Not only migration section. All database stuff. Both sections look the same.

**Comment by LukeTowers** [comment]
@yourwebmaker Off the top of my head the Traits section is different in October and it is helpful so I wouldn't suggest removing it. But, yes, I agree there are a lot of sections that are taken directly from the Laravel documentation and that could do with either linking to Laravel's own documentation or having additional information provided for October specific use cases.
