### ISSUE TITLE
[bug]: Unable to scroll fixed navigation sidebar

### ISSUE THREAD

**Issue by LukeTowers** [octobercms/docs#180]
When you are viewing a documentation page [like this for example](http://octobercms.com/docs/cms/themes), and you have the a sub listing open in the navigation sidebar, you are unable to scroll the sticky navigation sidebar independently of the main content area. This means that you have to scroll all the way to the bottom of the page just to view the rest of the navigation's items. As [some pages](http://octobercms.com/docs/database/traits) are quite long, this is very annoying and unfriendly to the user experience. 

The side bar should be made either not sticky or it should have a max height set (probably relative to viewport-height) with the overflow set to scroll so that the two components of the page could be scrolled independently of each other. 

As a side note, what would it take to get some really low level documentation setup in addition to the higher level tutorial style documentation that we have currently? I'm thinking of something along the lines of [Laravel's API documentation](https://laravel.com/api/5.1/index.html). Is this something where I could help contribute to the project by setting up such a system?

**Comment by daftspunk** [comment]
Fixed, thanks!
