### ISSUE TITLE
How to generate html docsets use current config?

### ISSUE THREAD

**Issue by reg2005** [octobercms/docs#182]
Hi! I translate into Russian. Than it is better to generate documentation?

**Comment by LukeTowers** [comment]
The documentation available at https://octobercms.com/docs is literally just mirrored into the `content/docs` directory of the OctoberCMS website AFAIK. Hopefully that helps, albeit a bit late.

**Comment by chrisvidal** [comment]
trying to replicate the same documentation system but I cant get it right.
I see a file `config/toc-docs.yaml`, how and where is used ?

**Comment by LukeTowers** [comment]
It's used by a simple PHP script on a CMS page to process & render the Table of Contents. I don't have access to it at the moment; but it shouldn't be too difficult to implement yourself.

**Comment by chrisvidal** [comment]
Thanks Luke. Yes i will figured this out with using the Yaml Parser class.
Last question is about how do you generate the pages themselves?
I am thinking to generate them instead of creating them manually and forget some.

**Comment by LukeTowers** [comment]
What do you mean how do you generate them? They're pulled in from the repo via git and added to the content directory

**Comment by chrisvidal** [comment]
the repo is meant to be in placed in the content folder right ?
it is purely content and it is not page (i dont see any page title, no page url, ) so I am guessing that there are pages holding that content somewhere.

**Comment by LukeTowers** [comment]
You'd use the TOC to get that information, and you would be using the content files as a static database rendering them as required on a CMS page through the `|md` filter

**Comment by chrisvidal** [comment]
What? i dont get you here.
to display the url cms/theme/installation you need a page with this url defined that will contains the tag `{% content 'docs/setup/installation ' %}`
to display the url cms/theme/configuration you need another page with this url defined that will contains the tag `{% content 'docs/setup/configuration ' %}`

and so forth. right ?

or is there a way to have only one page used for all ?
I am confused here

**Comment by LukeTowers** [comment]
@chrisvidal use URL parameters:
```
url="/docs/:path?*
==
{% content 'docs/' ~ this.param.path | md %}
```

**Comment by chrisvidal** [comment]
Holy Cow !
I didnt think about this at all. It makes sense.
Thanks Luke

**Comment by LukeTowers** [comment]
No problem

**Comment by chrisvidal** [comment]
in my case this works:
````
{% set docFile = 'docs/' ~ this.param['path?']|replace({'/' : '-'}) ~ '.md' %}
{% content docFile %}
````

**Comment by chrisvidal** [comment]
we cant use ````{% partial %}```` in content file ?

**Comment by LukeTowers** [comment]
Content files are fairly limited in what they can do, as they are just content. If you want partials, use partials to hold partials
