### ISSUE TITLE
Documentation for front-end user management

### ISSUE THREAD

**Issue by meysammahfouzi** [octobercms/docs#205]
There is no documentation, whatsoever, as to how one can manage users on front-end side. The only thing available (for those who want to learn doing this) is the source code of `rainlab.user-plugin` which is not self-explanatory enough. I mean come on! add some documentation for front-end user management! Or if you do not have time to do that, make [laravel's authentication API](https://laravel.com/docs/5.3/authentication) available to use! 

https://octobercms.com/forum/post/authentication-for-a-front-end-login-script
https://octobercms.com/forum/post/why-cant-use-the-auth-class-how-to-use-auth-for-front-end-user?page=1

October rocks, but not at user management. I have chosen to use OctoberCMS to make my life easier, but sometimes it doesn't.

**Comment by daftspunk** [comment]
Looks like the [published documentation](http://octobercms.com/plugin/rainlab-user) has gone stale against the most [up to date documentation](https://github.com/rainlab/user-plugin/blob/master/README.md). We'll fix this up. Thanks for the feedback!
