### ISSUE TITLE
Add "has-errors" class to div if Ajax Validation fails

### ISSUE THREAD

**Issue by jaycbrf4** [octobercms/docs#209]
My form element validates correctly but I am trying to add the class "has-errors" to the input group.

**Comment by LukeTowers** [comment]
@jaycbrf4 This issue does not make sense. Either ask for help on implementation details in the forums, IRC channel, or Slack team - or provide a clear explanation of what the issue with the documentation is.

**Comment by LukeTowers** [comment]
@jaycbrf4 Does this addition help? https://github.com/octobercms/docs/commit/e335ae18a8d04c18b04bdaf3431ddb0a5ef81f5a
