### ISSUE TITLE
Add Instructions for Properly Setting up OctoberCMS using Laravel's Official Vagrant Box - Homestead

### ISSUE THREAD

**Issue by GWSB** [octobercms/docs#221]
It seems a little silly that there's nothing in the docs explaining how to get set up with October using the officially supported local dev environment. 

I recognize that the config area explains how to set up nginx, as well as a few other important items. But it's not intuitive at all. There are a lot of people who blindly followed the instructions for setting Homestead up and may not know that these configurations could be the cause of their frustration after successfully running the auto installer.

OctoberCMS is promoted based off of it's simplicity. Given the large Laravel audience using homestead as their local environment, it would make sense to include instructions specifically pertaining to it in your docs.

Thanks!

**Comment by abstractFlo** [comment]
What you mean? Nothing especially to do to run october cms with homestead out of the box. You need no changes

**Comment by Eoler** [comment]
> OctoberCMS is promoted based off of it's simplicity. Given the large Laravel audience using homestead as their local environment, it would make sense to include instructions specifically pertaining to it in your docs.

Have you seen this: https://octobercms.com/blog/post/setting-local-october-cms-environment-vagrant-configuration-tutorial
That's simplicity!

**Comment by LukeTowers** [comment]
@abstractFlo Actually, there is a small gotcha when you use Homestead as your local environment; Homestead uses nginx, which means that if you want the server configuration rules to be applied properly (such as denying access to protected folders), you need to either take the whitelist approach by using a public directory or apply the nginx configuration rules to your project in Homestead.

**Comment by LukeTowers** [comment]
Given that nothing actionable was brought up, I'm assuming that this can be closed now.
