### ISSUE TITLE
Help with setting up public folder

### ISSUE THREAD

**Issue by SigalZ** [octobercms/docs#224]
Hi,

New to October. Using Wamp and php 5.6.25

Reading the configuration section I got stuck on this part: Using a public folder

When I ran the artisan command, I got the error:
symlink<>: Cannot create symlink, error code<1314>

The public folder was created, and I changed my httpd-vhosts file to point to the public folder.

My questions:

1. Which files should I move to the public folder?
2. When going live, do I upload these files to the public_html folder and the rest to the root?
3. What does this error I got mean?

Thank you

**Comment by LukeTowers** [comment]
This is a permissions error with the user that your WAMP web server is running as. It doesn't have the required permissions to create symbolic links (basically like desktop shortcuts, but used anywhere in your file system to link one location to the file contents that are actually located in another location).

You need to make sure that the user that WAMP is running as has permission to create symbolic links. See https://github.com/vova07/yii2-start/issues/81 for more information on doing so with IIS.

You don't move any files into the public folder, it will be automatically filled with all the required symlinks to the actual content. As far as deployment goes, I usually prefer to run the `october:mirror public` command on my deployment target, but if you want to be able to just upload and be done, then you need to make sure your symlinks are generated relatively by passing the relative flag (`artisan october:mirror public --relative`). Keep in mind that whenever you install a new theme or plugin, this command needs to be run again to regenerate the symlinked files within the public directory.

**Comment by SigalZ** [comment]
Thank you very much LukeTowers.

One more question please, how would I run the artisan command on the deployment target?

Is there an article somewhere that explains how to go live with October?

**Comment by LukeTowers** [comment]
You would use the command line / terminal / SSH to run the commands in the project directory.

I don't have any links to tutorials for working with the command line if you're completely new to that, but here's the docs on command line level commands that you can run with October http://octobercms.com/docs/console/commands

**Comment by SigalZ** [comment]
Thx, I will have to contact my hosting company to see how do I run console commands on their server
