### ISSUE TITLE
Parameters passed to the "getOptions" method

### ISSUE THREAD

**Issue by meysammahfouzi** [octobercms/docs#231]
According to [this answer on stackoverflow](http://stackoverflow.com/a/42684398/69537), there are some parameters passed to the "getOptions" method:

> The dataset is passed as the second argument to get the "getOptions" method

I failed to find it mentioned anywhere though. Has the above point been documented somewhere?

**Comment by LukeTowers** [comment]
It's not, I'll document it.

**Comment by LukeTowers** [comment]
Thanks for the report!

**Comment by meysammahfouzi** [comment]
@LukeTowers Thanks for improving the document!

**Comment by meysammahfouzi** [comment]
@LukeTowers That would be great if you could add an example usage of `$value` and `$formData`.
