### ISSUE TITLE
Related Model Extend Not Documented

### ISSUE THREAD

**Issue by MWalid** [octobercms/docs#232]
Regarding this [issue](http://stackoverflow.com/questions/43420515/octobercms-related-model-dynamic-default-value/).

It would be wonderful to add documentation with code sample.

Thank you,

**Comment by daftspunk** [comment]
This appears to be documented now

---
### Extending the View Widget

Provides an opportunity to manipulate the view widget.

For example you might want to toggle showCheckboxes based on a property of your model.

    public function relationExtendViewWidget($widget, $field, $model)
    {
        // Make sure the model and field matches those you want to manipulate
        if (!$model instanceof MyModel || $field != 'myField') {
            return;
        }

        if ($model->constant) {
            $widget->showCheckboxes = false;
        }
    }

### Extending the Manage Widget

Provides an opportunity to manipulate the manage widget of your relation.

    public function relationExtendManageWidget($widget, $field, $model)
    {
        // Make sure the field is the expected one
        if ($field != 'myField') {
            return;
        }

        // Manipulate widget as needed
    }

---

Thanks!
