### ISSUE TITLE
Nginx Configuration is wrong

### ISSUE THREAD

**Issue by ekrokowski** [octobercms/docs#242]
The current docs about Nginx config says:
```
rewrite ^themes/.*/(layouts|pages|partials)/.*.htm /index.php break;
rewrite ^bootstrap/.* /index.php break;
rewrite ^config/.* /index.php break;
rewrite ^vendor/.* /index.php break;
rewrite ^storage/cms/.* /index.php break;
rewrite ^storage/logs/.* /index.php break;
rewrite ^storage/framework/.* /index.php break;
rewrite ^storage/temp/protected/.* /index.php break;
rewrite ^storage/app/uploads/protected/.* /index.php break;
```

Those locations actually have to be prefixed with `/` to make them work:

```
rewrite ^/themes/.*/(layouts|pages|partials)/.*.htm /index.php break;
rewrite ^/bootstrap/.* /index.php break;
rewrite ^/config/.* /index.php break;
rewrite ^/vendor/.* /index.php break;
rewrite ^/storage/cms/.* /index.php break;
rewrite ^/storage/logs/.* /index.php break;
rewrite ^/storage/framework/.* /index.php break;
rewrite ^/storage/temp/protected/.* /index.php break;
rewrite ^/storage/app/uploads/protected/.* /index.php break;
```

**Comment by daftspunk** [comment]
Someone confirm this, then submit a pull request.

**Comment by LukeTowers** [comment]
Also we still need the configuration section for disallowing PHP file execution on Nginx to be added. I believe @dshoreman was going to test his config then provide it?

**Comment by dshoreman** [comment]
I was, until real life got in the way for reasons I won't go into here. Consequently, it's been a long time since I've worked with October - to the point where I've even hidden all plugins and themes from the Marketplace.

It's unlikely I'd be able to test this any time soon, so if anyone else is running Nginx feel free to chime in.

**Comment by LukeTowers** [comment]
No worries @dshoreman, I hope everything works out for you. Would you be willing to paste the configuration you were working on as a base for someone else to test?

**Comment by dshoreman** [comment]
@LukeTowers Sure, gist here: https://gist.github.com/dshoreman/f633063f4f0739dafe5289b8e8b68de4

Lines 24-26 could well be commented for reasons similar to what this issue aims to fix.

The script blocking magic happens on lines 33-35.

The first server block simply redirects to https - you could quite easily remove that along with the `ssl_*` rules and change `listen 443 ssl;` to `listen 80;` if you didn't want that.

**Comment by cjbrooks12** [comment]
For the record, I just deployed OctoberCMS successfully to nginx on Ubuntu 16.04 LTS using the current rewrite rules (without the leading `/`). Perhaps the docs should just include a note that a leading `/` _may_ be necessary, but try first without it?

**Comment by LukeTowers** [comment]
Thanks for your input @cjbrooks12!

**Comment by ndcisiv** [comment]
I've got a couple OctoberCMS installations running on Ubuntu 16.04 LTS, PHP 7.0.22, Nginx 1.10.3, and MariaDB 10.0.31.  I have the default config without the leading / and everything works perfectly.

**Comment by daftspunk** [comment]
Looks like nginx is pretty up to date these days
