### ISSUE TITLE
Only mailables may be queued

### ISSUE THREAD

**Issue by firemankurt** [octobercms/docs#246]
Error when trying to use documented Mail::queue()
See: https://octobercms.com/docs/services/mail#queueing-mail

Causes error:
"Only mailables may be queued." on line 354 of /site_directory/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php"

Need to update Docs to include creating Mailables per: https://laravel.com/docs/5.4/mail#generating-mailables

Should include where to save mailable classes in plugin directory.

**Comment by LukeTowers** [comment]
@firemankurt did this get fixed in the octobercms/october repository?

**Comment by daftspunk** [comment]
This was fixed some time ago. If this is still occurring, ping me and we can revisit. Thanks!
