### ISSUE TITLE
Controllers-Ajax documentation

### ISSUE THREAD

**Issue by datune** [octobercms/docs#263]
The documentation refers to "controller behaviours below", but there is nothing on that subject to be found.

https://octobercms.com/docs/backend/controllers-ajax#passing-data-to-views

**Comment by LukeTowers** [comment]
I believe it's talking about https://octobercms.com/docs/services/behaviors. Could you make a PR to update the wording and link to the correct page?

**Comment by LukeTowers** [comment]
Fixed by #264
