### ISSUE TITLE
url regex example in docs does not work

### ISSUE THREAD

**Issue by john-mark-wilkinson** [octobercms/docs#27]
In the url example of the "pages" docs, the following is given as an example of using regex in page verification: "/blog/:post_name?|^[a-z0-9\-]+$".

However, if you put that in the url when creating a page, you get the following error message:

"Invalid URL format. The URL should start with the forward slash symbol and can contain digits, Latin letters and the following symbols: _-[]:?|/+*".

This apparently disallows the '^' and '$' symbols....?

**Comment by daftspunk** [comment]
Confirmed this has been fixed / no longer occurs
