### ISSUE TITLE
{% page %} tag missing from documentation

### ISSUE THREAD

**Issue by hlev** [octobercms/docs#338]
https://octobercms.com/docs/markup/tag-placeholder#checking-placeholder-exits contains a `{% page %}` tag in its example code, but the documentation does not mention this tag.

I found the corresponding parser, node and the comment https://github.com/octobercms/october/blob/master/modules/cms/twig/PageTokenParser.php
https://github.com/octobercms/october/blob/master/modules/cms/twig/PageNode.php

```
    /**
     * Renders a page.
     * This function should be used in the layout code to output the requested page.
     * @return string Returns the page contents.
     */
    public function pageFunction() { ... }
```

Have not studied the internals of the CMS enough yet to figure out what this is for. Until now I thought that normally pages specify their layout in their meta markup.

```
layout = "default"
==
```

My guess is that this tag's purpose could be for the other way around, to call a layout from code and specify a page as parameter to be displayed within the layout?

**Comment by LukeTowers** [comment]
@hlev see https://octobercms.com/docs/cms/layouts#introduction. `{% page %}` is used to output the page content in layouts. Feel free to submit it to the docs with an explanation of that though

**Comment by hlev** [comment]
@LukeTowers _{% facepalm %}_ Thanks, despite having built our site with OctoberCMS I "managed" to avoid this basic detail and got thrown off by our layout that does not include raw markup from a page, instead uses partials and user defined placeholders exclusively.

> Feel free to submit it to the docs with an explanation of that 

I will, for the sake of completeness, thanks!
