### ISSUE TITLE
Here's some extra info to help Dev's speed up October CMS Loading

### ISSUE THREAD

**Issue by ayumihamsaki** [octobercms/docs#349]
October CMS tells developers to add the following code at the bottom of the web pages - to allow the October AJAX and some other things to work, see here:

```html
{% framework extras %}
{% scripts %}  
```

## Making October CMS Load Faster

You can preload these files to speed up the loading of October CMS by adding the following two lines of code in your `<head>` section, e.g.

```html
<link rel="preload" href="https://example.com/modules/system/assets/css/framework.extras-min.css" as="style">

<link rel="preload" href="https://example.com/modules/system/assets/js/framework.combined-min.js" as="script">
```

I would like to write a pr to add this extra information in the doc's. I think it should be added to this doc's web page found here: https://octobercms.com/docs/ajax/introduction#framework-script

**Comment by ayumihamsaki** [comment]
@LukeTowers Please review and happy new year.

**Comment by LukeTowers** [comment]
@ayumihamsaki is there any benefit to just adding `rel="preload"` directly to the output of `{% framework %}` internally?

**Comment by ayumihamsaki** [comment]
@LukeTowers Yes there would be a benefit to loading it directly. Adding the `rel="preload"` would make the waiting gap before the loading of the assets zero in waiting time! So instead of waiting for the previous assets to load it would load straight after the HTML asset has been loaded. On average running tests on a 4G network I lose around 1 second of waiting time and 2.5 seconds of waiting time for a regular 3G network, so it's worth doing it. These results are from webpagetest.

> is there any benefit to just adding rel="preload" directly to the output of {% framework %} internally?

To answer your question directly, Yes it would give benefits to all users! However, `rel-preload` must be loaded inside the `<head>` tag so it must be injected there. If that is possible I can open an issue in the octobercms github for that.

**Comment by ayumihamsaki** [comment]
p.s. Let me know what you think. I might just close this issue here and open it up in the octobercms github instead.

**Comment by ayumihamsaki** [comment]
@LukeTowers Yes there would be a benefit to loading it directly. Adding the `rel="preload"` would make the waiting gap before the loading of the assets zero in waiting time! So instead of waiting for the previous assets to load it would load straight after the HTML asset has been loaded. On average running tests on a 4G network I lose around 1 second of waiting time and 2.5 seconds of waiting time for a regular 3G network, so it's worth doing it. These results are from webpagetest.

> is there any benefit to just adding rel="preload" directly to the output of {% framework %} internally?

To answer your question directly, Yes it would give benefits to all users! However, `rel-preload` must be loaded inside the `<head>` tag so it must be injected there. If that is possible I can open an issue in the octobercms github for that.

## This is correct way

```html
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>Correct Method 1</title>

<link rel="preload" href="https://example.com/modules/system/assets/css/framework.extras-min.css" as="style">

<link rel="preload" href="https://example.com/modules/system/assets/js/framework.combined-min.js" as="script">

</head>

<body>

..

{% framework extras %}
{% scripts %} 

</body>
</html>
```

into

```html
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>Correct Method 2</title>

<link rel="preload" href="https://example.com/modules/system/assets/css/framework.extras-min.css" as="style">

<link rel="preload" href="https://example.com/modules/system/assets/js/framework.combined-min.js" as="script">

</head>

<body>

..

<script src="/modules/system/assets/js/framework.combined-min.js"></script>
<link rel="stylesheet" property="stylesheet" href="/modules/system/assets/css/framework.extras-min.css">

</body>
</html>
```

## This is NOT a correct way

```html
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>Not Correct Method 1</title>

</head>

<body>

..

<script rel="preload" src="/modules/system/assets/js/framework.combined-min.js" as="script"></script>
<link rel="stylesheet preload" property="stylesheet" href="/modules/system/assets/css/framework.extras-min.css" as="style">

</body>
</html>
```

You can not injected it like that, the `rel-preload` needs to be 1. separate link-tag code and 2. in the <head>. Giving a total of 4 lines of code.

p.s. Let me know what you think. I might just close this issue here and open it up in the octobercms github instead.

**Comment by LukeTowers** [comment]
Open a PR instead of an issue please. `{% framework %}` is typically supposed to be the head anyways

**Comment by ayumihamsaki** [comment]
Opened github here: https://github.com/octobercms/october/issues/4030

Will close this one.
