### ISSUE TITLE
Event Inconsistencies with mail.send

### ISSUE THREAD

**Issue by Humni** [octobercms/docs#360]
I believe the docs are wrong with this event, the parameters specified in the docs are flipped for the mailer instance event and the Illuminate event

**Current Documentation in the Code (matches the [documentation](https://octobercms.com/docs/api/mailer/send))**
```
        /**
         * @event mailer.send
         * Fires after the message has been sent
         *
         * Example usage (logs the message):
         *
         *     Event::listen('mailer.send', function ((string) $view, (\Illuminate\Mail\Message) $message) {
         *         \Log::info("Message was rendered with $view and sent");
         *     });
         *
         * Or
         *
         *     $mailerInstance->bindEvent('mailer.send', function ((\October\Rain\Mail\Mailer) $mailerInstance, (string) $view, (\Illuminate\Mail\Message) $message) {
         *         \Log::info("Message was rendered with $view and sent");
         *     });
         *
         */
        $this->fireEvent('mailer.send', [$view, $message]);
        Event::fire('mailer.send', [$this, $view, $message]);
```

The issue is that the `Event::fire();` has the parameters that are documented for `$mailerInstance->bindEvent()`. 

**Solution 1:** Fix the documentation to match current code behaviour
**Solution 2:** Change the code to match the documentation

I'm happy to provide a PR for either one. Just let me know what way you would like this handled.

**Comment by LukeTowers** [comment]
@Humni good catch. Docs are wrong, flip em! Thanks! :)
