### ISSUE TITLE
Outdated content for extending form ?

### ISSUE THREAD

**Issue by aurelien-roy** [octobercms/docs#401]
It seems two different pages of the doc gives two different solutions for extending a backend form.

### Page 1 "Backend > Extending Plugins ":
[https://octobercms.com/docs/plugin/extending#extending-backend-form](https://octobercms.com/docs/plugin/extending#extending-backend-form)
Here it is advised to listen the "**backend.form.extendFields**" (or the "**backend.form.extendFieldsBefore**") event. I believe this way of doing it is outdated.

### Page 2 "Backend > Forms" :
[https://octobercms.com/docs/backend/forms#extend-form-fields](https://octobercms.com/docs/backend/forms#extend-form-fields)
Here it is advised to use the **extendFormFields** method (which I believe is a newer way of doing the same thing).

### Proposed solution :

- Make sure the extendFormFields method can replace both extendFields and extendFieldsBefore events.
- Remove the "extending form" section from the "Backend > Forms" (instead add a link referencing the "Extending Plugins" pages.
- Edit the "Extending Plugins" page to use the **extendFormFields** method instead of the event listening method.

**Comment by LukeTowers** [comment]
@aurelien-roy both methods are valid in different ways. `extendFormFields()` is only available on a controller class and actually hooks into those events and is essentially just an easier way of limiting the listener for you: https://github.com/octobercms/october/blob/master/modules/backend/behaviors/FormController.php#L865
