### ISSUE TITLE
Doc's not very helpful explaining passing parameters in form tag

### ISSUE THREAD

**Issue by ayumihamasaki2019** [octobercms/docs#410]
The following web page: https://octobercms.com/docs/markup/function-form

Is not very helpful explaining how to pass parameters through the `form` tag. In the end I had to go to the Laravel web site and read their doc's.

Here is a basic example of what I'm taling about:

```php
<?= Form::open(array('id' => 'example', 'class' => 'something')) ?>
..
<?= Form::close() ?>
```

I think it would be helpful to people to add this kind of information into the doc's to help people wanting to pass parameters via php.

**Comment by LukeTowers** [comment]
@ayumihamasaki2019 make a PR and I'll review it
