### ISSUE TITLE
Doc Backend Lists not open.

### ISSUE THREAD

**Issue by prhost** [octobercms/docs#423]
Doc Backend Lists not open. Browser Version 1.0.1 Chromium: 78.0.3904.108 (Official Build) (64-bit) and Safari Version 13.0.4 (13608.4.9.1.4)

![Screen Shot 2019-12-12 at 12 10 33](https://user-images.githubusercontent.com/3984760/70723999-982fbb00-1cd8-11ea-99f5-c0e9f964529d.png)

**Comment by jeremymouton** [comment]
Seeing this too.
