### ISSUE TITLE
Queued closures were deprecated in L5.3

### ISSUE THREAD

**Issue by scottbedard** [octobercms/docs#425]
Our documentation appears to be out of date with regard to queueing closures.
https://octobercms.com/docs/services/queues#queueing-closures

This functionality was removed in L5.3, and appears to have been restored in L6
https://laravel.com/docs/5.3/upgrade#upgrade-5.3.0
https://laravel.com/docs/6.x/queues#queueing-closures

We should probably leave a note in the docs saying that this is no longer supported, but likely will be again when the L6 upgrade lands

**Comment by daftspunk** [comment]
It's been there for years and nobody has seemed to notice, it should be OK to leave it for another couple of weeks (months?) while we upgrade L6. This is certainly some more incentive to do that

**Comment by LukeTowers** [comment]
Note this was added back in 5.7 (https://github.com/laravel/framework/commit/556b948c41b273144e5f23f6b3b6167bf7e0c84e & https://github.com/laravel/framework/pull/25777).

**Comment by daftspunk** [comment]
The docs are now referring to an L6 build so we can close this. Thanks!
