### ISSUE TITLE
Coding error with <code> wrapping headers and text

### ISSUE THREAD

**Issue by summercms** [octobercms/docs#430]
URL: https://octobercms.com/docs/api/october/rain/support/readme

![image](https://user-images.githubusercontent.com/57409060/71670789-ff391080-2d68-11ea-89a0-9624d7c2dbf8.png)

another screenshot of same web page:

![image](https://user-images.githubusercontent.com/57409060/71670992-a5851600-2d69-11ea-8354-ec32812e6192.png)

Notice the header sizes getting smaller and smaller due to an open `<code>` tag wrapping the header and text etc.

~~I might try and write a pr for this today, seems a small issue.~~

My bad, I don't have access to the main website. Easy to fix just remove the extra `<code>` wrapper on each section.

**Comment by LukeTowers** [comment]
@ayumi-cloud this file is available here: https://github.com/octobercms/library/blob/master/src/Support/README.md, although @daftspunk this looks like an issue with the website's parser of the MD files
