### ISSUE TITLE
array_where() example closure has arguments reversed

### ISSUE THREAD

**Issue by bcwaretx** [octobercms/docs#437]
docs/services/helpers#method-array-where

array_where wraps Laravel Arr::where()
https://laravel.com/docs/5.5/helpers#method-array-where
which in turn wraps array_filter()

Documented arguments for the closure are `function ($value, $key)`. Current documentation lists `function ($key, $value)`.

**Comment by daftspunk** [comment]
Thanks @bcwaretx !
