### ISSUE TITLE
`softDelete` flag is needed for deleting related models on relationship when related model is implemented `SoftDelete`.

### ISSUE THREAD

**Issue by joelamltc** [octobercms/docs#450]
When you delete a model and also want to delete its related models, but the related model is implemented  `October\Rain\Database\Traits\SoftDelete`. 
A correct relationship definition should be like this:
```
public $hasMany = [
    'relation_name' => [
        Model::class,
        'key'        => 'id',
        'delete'     => true,
        'softDelete' => true, // this is needed in order to delete `SoftDelete` Model.
    ],
];
```
But this one is never been documented.

**Comment by bennothommo** [comment]
@joelamltc Would you be willing to submit a PR adding that to [the docs](https://github.com/octobercms/docs/blob/master/database-traits.md) for us?

**Comment by bennothommo** [comment]
Actually, scratch that - the `softDelete` flag is mentioned here: https://github.com/octobercms/docs/blob/master/database-traits.md

**Comment by joelamltc** [comment]
@bennotthommo
Sorry for overlooks.
