### ISSUE TITLE
The doc's are missing the available Navigation menus properties

### ISSUE THREAD

**Issue by ayumi-cloud** [octobercms/docs#467]
Link to the doc's: https://octobercms.com/docs/plugin/registration#navigation-menus

October has the following default properties:

```
Array
(
    [example] => Backend\Classes\SideMenuItem Object
    (
        [code] => example
        [owner] => Acme.Plugin
        [label] => acme.plugin::lang.menu.example.title
        [icon] => fas fa-users-cog
        [iconSvg] =>
        [url] => https://www.example.com/acme/plugin/example
        [counter] =>
        [counterLabel] =>
        [badge] =>
        [order] => 30
        [attributes] => Array
        [group] => widgets
    (
    )
        [permissions] => Array
        (
            [0] => acme.plugin.example
        )
    )
)
```

There is no mention of the `default` properties in the doc's.

It would be nice to have a table in the doc's listing the `default` properties available with descriptions on their usage for newbie's.

e.g.

property | description
---|---
icon | displays an icon in the navigation menu, choose an icon from October's default icon list found here: [October Icons](https://octobercms.com/docs/ui/icon)

p.s. I got no idea what `counter`, `counterLabel` and `badge` do and so I went to the doc's to check and couldn't find anything so ended up opening this issue.

**Comment by bennothommo** [comment]
@ayumi-cloud Would you be willing to create a PR documenting this? They're [documented in the NavigationManager](https://github.com/octobercms/october/blob/develop/modules/backend/classes/NavigationManager.php#L153-L183), so it'd just be a case of converting that documentation and formatting it for the docs.

**Comment by LukeTowers** [comment]
Closed by https://github.com/octobercms/docs/pull/468
