### ISSUE TITLE
Improved get started documentation and required permissions to run OctoberCMS

### ISSUE THREAD

**Issue by hitchhooker** [octobercms/docs#469]
Getting OctoberCMS backendup and running to run is always a multihour headbanger for me and in the end I do not even know why I got it to work and is my installation safe at all, because I have spammed permission changes based on search results. This is very much due the lack of proper Get started documentation for terminal users. 
I would love to write pull request for this but as I said im still fucking lost about correct commands.

**Comment by bennothommo** [comment]
@hitchhooker I've seen that you've been in discussions with @LukeTowers on Discord about this so I'm gonna close this. If you have a suggestion as to any details the documentation may be lacking in this respect, please feel free to comment and I'll re-open.
