### ISSUE TITLE
Types missing from plugin-components.md

### ISSUE THREAD

**Issue by SplicedWeb** [octobercms/docs#471]
Noticed recently there are not all types showing in the documentation here: 
[Plugin Component Properties](https://octobercms.com/docs/plugin/components#component-properties)
String, checkbox and dropdown are listed only.

They are mentioned here
[docs ui inspector](https://octobercms.com/docs/ui/inspector)

Within the blog 
[Inspector 2.0](https://octobercms.com/blog/post/inspector-2)
stringList, text, object, objectList, dictionary, stringautocomplete etc are mentioned.  Should they be added to documentation?

**Comment by daftspunk** [comment]
Documentation for this has been added in v3:

https://docs.octobercms.com/3.x/element/inspector-types.html

Best regards
