### ISSUE TITLE
The width of Field columns are very small

### ISSUE THREAD

**Issue by gergo85** [octobercms/docs#476]
![issue](https://user-images.githubusercontent.com/2959112/92567768-76bb2a00-f27e-11ea-814b-9fb0a669a530.jpg)

**Comment by LukeTowers** [comment]
Where's the typo?

**Comment by gergo85** [comment]
Sorry. Not typo. The width of Field column is very small.

**Comment by bennothommo** [comment]
@LukeTowers @daftspunk might be related to this CSS in the docs:

```
.article {
    overflow-wrap: anywhere;
}
```

Unticking that in dev tools seems to make everything flow nicely again.

**Comment by mjauvin** [comment]
I asked Sam to add that to fix the docs pages on mobile.

Didn't expect this to break on table headers.

**Comment by mjauvin** [comment]
Documentation pages on mobile were bleeding and made the page scroll horizontally.

**Comment by bennothommo** [comment]
Ah fair enough @mjauvin. Perhaps the rule could be applied for mobile only through a `@media` query.

**Comment by mjauvin** [comment]
It wouldn't help as it also breaks the above page on mobile...

I'll try to exclude th/thead tags, that will fix the issue.

**Comment by mjauvin** [comment]
This new CSS rule should fix the issue:
```
.article th,
.article td {
   overflow-wrap:normal;
}
```

**Comment by daftspunk** [comment]
Should be fixed now
