### ISSUE TITLE
Is it possible to make the custom validation messages a bit easier to find in the doc's

### ISSUE THREAD

**Issue by ayumi-cloud** [octobercms/docs#481]
So I was reading the doc's and writing the following code in the models section php file.

Something like this:

```php
class User extends Model
{
    public $messages = [
       'name.required' => 'The :attribute field is required.',
        ...
    ];
}
```

Basically I started my reading of the doc's here: https://octobercms.com/docs/services/validation#custom-error-messages

Tested it and it didn't work.

So I did some more digging through Google as the search engine in the October CMS website kept sending me to that page.

Thanks to Google after about 50 different searches I came across the **Traits** page here: https://octobercms.com/docs/database/traits#custom-error-messages

And found the following code:

```php
class User extends Model
{
    public $customMessages = [
       'name.required' => 'The :attribute field is required.',
        ...
    ];
}
```

Is it possible to put on the main Validation page of the doc's a note saying October doesn't use `public $messages` and instead uses `public $customMessages` for adding custom messages to the models file.

I basically wasted an hour digging through all the doc's because it's kind of hidden away.

Also add an `array` example to the custom validation messages as well.

```php
public $rules = [
        'links.*.url' => [ 'required', 'url' ],
];

public $customMessages = [
       'links.*.url.*' => 'Error with URL field',
];
```

and/or

```php
public $rules = [
        'links.*.url' => [ 'required', 'url' ],
];

public $customMessages = [
       'links.*.url.required' => 'The URL is required',
];
```

etc.

**Comment by LukeTowers** [comment]
Feel free to submit a PR, this is why the docs are open source too

**Comment by ayumi-cloud** [comment]
@LukeTowers 

![image](https://user-images.githubusercontent.com/57409060/94337491-a12d1700-ffe2-11ea-9006-a76140e0a491.png)

**Comment by LukeTowers** [comment]
Those two things are different though, the Validation service is the underlying logic that powers the Validation trait, the validation trait is essentially syntactic sugar on top of the validation service meant specifically for models.

**Comment by ayumi-cloud** [comment]
@LukeTowers `syntactic sugar` lol.

### Laravel Validation Section

![image](https://user-images.githubusercontent.com/57409060/94361019-47dbeb00-00a9-11eb-8e9d-a9c0bfa5bc60.png)

### Plugin Validation Section

![image](https://user-images.githubusercontent.com/57409060/94361113-dc464d80-00a9-11eb-886d-785b7531a826.png)

### Trait Section

![image](https://user-images.githubusercontent.com/57409060/94361130-f41dd180-00a9-11eb-8f8b-78ae36ba9c90.png)

(*) `array` examples added to plugin and trait section as well.

**Comment by LukeTowers** [comment]
Hmm, I think it would probably be better just to link to the validation trait page from the models page, since that's what the docs are for, not for "plugin validation"

**Comment by bennothommo** [comment]
Definitely do not agree with there being a Validation page under Plugins, validation happens everywhere - not just within plugins. I personally find the validation docs to be easy to find - Validation after all is a service, and if you recognise the models using a trait, then the Traits section is easy to find too.

While I agree that maybe a link between the pages could be made, and the content could be updated to include more recent updates to validation ([such as this](https://github.com/octobercms/docs/pull/473)), I don't think the placement of the pages needs to change.

**Comment by ayumi-cloud** [comment]
@LukeTowers @bennothommo 

No problem understand what you both are saying. Will submit a pr just for the `array` codes examples.

Just going to ask (I'm sure it will be ok). I want to hard fork the doc's and write my own custom notes etc over the top and merge some October Tips into the doc's and convert it into using html language from markdown etc. Just thought I'd be transparent and say it - I'm sure you guys will be fine with it. Also at a later date need to start merging into the October II api doc's etc.

**Comment by LukeTowers** [comment]
@ayumi-cloud sounds good. FYI for your fork if you want to publicly release it you can't call it "October II". The project is MIT licensed but the name, brand, & logo belong to us.

**Comment by ayumi-cloud** [comment]
Ah ok I will put it under a project code name.

**Comment by ayumi-cloud** [comment]
Yah it will be public, I will put it under a project code name instead to full fill the license agreement. The hard forking of the doc's is more of a learning curve thing for me to better understand Laravel and I just want to write custom notes everywhere...
