### ISSUE TITLE
PHP version in public docs is incorrect but in setup-installation.md is ok

### ISSUE THREAD

**Issue by xseguib** [octobercms/docs#489]
If you follow the setup installation steps it says that you need PHP version 7.0.8 or higher but should be 7.2 or higher as composer.json says or setup.installation.md

![2020-10-21_12h57_23](https://user-images.githubusercontent.com/11737272/96711198-7a71be80-139d-11eb-84eb-c941c65424c6.png)

**Comment by bennothommo** [comment]
@xseguib The October CMS docs on octobercms.com are usually updated each stable version. October CMS 1.1.0 and 1.1.1 are edge releases - it is these versions that require PHP 7.2. If you are using a 1.0.x version of October CMS, you are fine with PHP 7.0.8 or above.

**Comment by LukeTowers** [comment]
@xseguib Just to clarify @bennothommo's comment, the marketplace docs are updated with stable _marketplace_ releases. v1.1.0 is a stable update but is only available through composer right now.
