### ISSUE TITLE
Add custom file name config information

### ISSUE THREAD

**Issue by mkinternet** [octobercms/docs#527]
https://github.com/octobercms/docs/blob/develop/1.x/plugin/settings.md

/plugins/author/myplugin/config/custom.php 
becomes
Config::get('Acme.Demo::custom.maxItems');

**Comment by daftspunk** [comment]
Thanks. Added this to docs

---

You may also use a different filename for the configuration file and this affects the key name. For example, a configuration file named **custom.php** will prefix the key name with `custom`, using the following format: **Acme.Demo::custom.maxItems**. Example configuration file **plugins/acme/demo/config/custom.php**.

```php
$maxItems = Config::get('acme.demo::custom.maxItems', 50);
```
