### ISSUE TITLE
a slight deficiency

### ISSUE THREAD

**Issue by ZhiweiWu0425** [octobercms/docs#537]
Not enough quantity (of course this is not a big problem)
![image](https://user-images.githubusercontent.com/89636889/149614318-06f50700-aee3-4169-a60a-64d0c21cf63f.png)

**Comment by daftspunk** [comment]
Thanks for the report. This is fixed

![image](https://user-images.githubusercontent.com/1392869/149682940-ba29b349-b7b7-4ecc-ae4b-c0d81ad3c248.png)
