### ISSUE TITLE
File Attachments - attachMany - validation example - forceSave needed

### ISSUE THREAD

**Issue by mesiarm** [octobercms/docs#567]
Add warning to documentation, that you need use forceSave() instead of save() when using validation on attach many, instead validation fails. I was still getting error without forceSave(), also mentioned here: https://octobercms.com/forum/post/the-validation-rules-dont-work-properly-with-file-uploading?page=2

**Comment by daftspunk** [comment]
This doesn't look like a bug. The `forceSave` method is documented here: https://docs.octobercms.com/2.x/database/traits.html#overriding-validation
