### ISSUE TITLE
Dead links on Configuration > CSRF chapter

### ISSUE THREAD

**Issue by adrenth** [octobercms/docs#574]
The CSRF chapter https://docs.octobercms.com/3.x/setup/configuration.html#csrf-protection contains dead links:

- https://docs.octobercms.com/3.x/services/html.html#opening-a-form
- https://docs.octobercms.com/3.x/services/html.html#form-tokens

**Comment by daftspunk** [comment]
This is fixed in: https://github.com/octobercms/docs/commit/4ded6716beaf06016d900f10040d2ea61efad6e8

Thanks!
