### ISSUE TITLE
Ajax extra features are gone

### ISSUE THREAD

**Issue by prhost** [octobercms/docs#582]
Before there was an access menu for Extra features, the menu disappeared, and when clicking on this link it goes to the introduction of the session.

![Screenshot 2023-03-27 at 16 53 36](https://user-images.githubusercontent.com/3984760/228051757-38a6037e-4485-4786-8e60-68cb14025ada.png)

**Comment by daftspunk** [comment]
This page was replaced by the entire "Features" section in the left hand menu. The extra features are mentioned in the introduction so it seems relevant to link here now.
