### ISSUE TITLE
Add version independent links please

### ISSUE THREAD

**Issue by frank-laemmer** [octobercms/docs#588]
Feature request to allow to link to this:

* https://docs.octobercms.com/setup/installation.html

So that it redirects to the latest version available, currently https://docs.octobercms.com/3.x/setup/installation.html

Example:

* https://laravel.com/docs/installation

Why? It allow third party providers (like us) to always have an up-to-date link to your current install guides.

**Comment by daftspunk** [comment]
Hey @frank-laemmer 

This link is a legacy one and is kept in place for SEO purposes: https://docs.octobercms.com/setup/installation.html

The entry point for the docs should be https://docs.octobercms.com/ as a generic link to the documentation.

We've improved the docs to redirect version-less links to their nearest/latest article. So https://docs.octobercms.com/setup/installation.html should now redirect to https://docs.octobercms.com/3.x/setup/installation.html



I hope this helps.
