### ISSUE TITLE
[Enhancement] Search box

### ISSUE THREAD

**Issue by Sylvert0** [octobercms/docs#64]
It's possible to add a search box to the docs page? So when you need search something and you don't know where it's, you can found easily.

**Comment by daftspunk** [comment]
Feature noted, thanks. Use google for now

```
site:octobercms.com model relations
```

**Comment by FelixINX** [comment]
I know that MkDocs (probably what is used here) has a search function. [Docs](http://www.mkdocs.org/user-guide/styling-your-docs/#search-and-themes)

**Comment by FelixINX** [comment]
Done!
