### ISSUE TITLE
Form Widget needs clarification from a plugin instal context

### ISSUE THREAD

**Issue by goradiantweb** [octobercms/docs#7]
Plugin form Widget's can pretty much be structured however dev's wish.

It would be sensical to articulate recommended file placement.

To which I believe should be:

/plugins/authorname/pluginname/modules/backend/formwidgets/widgetname

**Comment by daftspunk** [comment]
We have a handy scaffold command for this now!

``php artisan create:formwidget Plugin.Name FormWidgetName``

Should take care of it!
